# ---------------------------------------------------------------------------
# Networking: use the account's default VPC/subnet in var.aws_region.
# ---------------------------------------------------------------------------
data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }

  filter {
    name   = "default-for-az"
    values = ["true"]
  }
}

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# ---------------------------------------------------------------------------
# SSH key pair - generated by Terraform. Private key is exposed via a
# sensitive output; save it locally and keep it out of version control.
# ---------------------------------------------------------------------------
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = var.key_pair_name
  public_key = tls_private_key.ssh.public_key_openssh
  tags       = var.tags
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.ssh.private_key_pem
  filename        = "${path.module}/${var.key_pair_name}.pem"
  file_permission = "0600"
}

# ---------------------------------------------------------------------------
# Security group: allow SSH from the admin CIDR only, and all outbound
# traffic (needed to reach Atlas over TLS on 27017 and to install packages).
# ---------------------------------------------------------------------------
resource "aws_security_group" "app" {
  name        = "proplist-app-sg"
  description = "PropList EC2 app instance - SSH from admin CIDR, all outbound"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH from admin CIDR"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.ssh_admin_cidr]
  }

  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = var.tags
}

# ---------------------------------------------------------------------------
# EC2 instance: 4 vCPU / 8 GiB RAM (c6i.xlarge by default), Amazon Linux
# 2023, with Amazon Corretto (Java) installed via user_data.
# ---------------------------------------------------------------------------
resource "aws_instance" "app" {
  ami                         = data.aws_ami.al2023.id
  instance_type               = var.ec2_instance_type
  subnet_id                   = data.aws_subnets.default.ids[0]
  vpc_security_group_ids      = [aws_security_group.app.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true

  root_block_device {
    volume_size = 250
    volume_type = "gp3"
    tags        = var.tags
  }

  user_data = <<-EOF
    #!/bin/bash
    set -euxo pipefail
    dnf update -y
    dnf install -y "java-${var.java_version}-amazon-corretto-devel"
    java -version

    # Prevent sshd from dropping idle SSH sessions: send a keepalive probe
    # to the client every 60s, and only give up after 1440 consecutive
    # unanswered probes (24h) - mirrors the ServerAliveInterval/CountMax
    # settings on the client side, so idle terminals (e.g. long-running
    # bootstrap.sh, data generation) don't get disconnected mid-session.
    cat >> /etc/ssh/sshd_config <<'SSHD'

    ClientAliveInterval 60
    ClientAliveCountMax 1440
    SSHD
    systemctl reload sshd
  EOF

  tags = merge(var.tags, {
    Name = "proplist-app"
  })
}

# ---------------------------------------------------------------------------
# Elastic IP: static public address for the instance, referenced by the
# Atlas project IP access list so it doesn't change across instance
# stop/start cycles.
# ---------------------------------------------------------------------------
resource "aws_eip" "app" {
  instance = aws_instance.app.id
  domain   = "vpc"
  tags     = var.tags
}
